[tool.poetry]
name = "dta-python"
version = "1.0.0"
description = "A lightweight method for detecting extremely low-proportion dt in backbone networks."
authors = ["alpinebuster <imzqqq@hotmail.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Communications :: Tor",
]
package-mode = false  # Disable packaging mode, only for dependency management

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
# priority = "primary"
priority = "supplemental"
[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = "supplemental"
[[tool.poetry.source]]
name = "nvidia"
url = "https://pypi.nvidia.com"
priority = "explicit"


[tool.poetry.dependencies]
python = ">=3.12,<3.15"
ipykernel = "^7.1.0"
pytest = "^9.0.2"
setuptools_rust = ">=1.12.0"
attrs = "^25.4.0"
numpy = "^2.4.1"
fastai = "^2.8.6"
scikit-learn = "^1.8.0"
scipy = "^1.17.1"
scipy-stubs = {extras = ["scipy"], version = "^1.17.1.0"}
pandas = "^3.0.0"
pandas-stubs = "^3.0.0.260204"
ipywidgets = "^8.1.7"
seaborn = "^0.13.2"
requests = "^2.32.5"
matplotlib = "^3.10.8"
tqdm = "^4.67.1"
opencv-python = "^4.10.0.84"
pyyaml = "^6.0.2"
tensorboard = "^2.20.0"
torch-tb-profiler = "^0.4.3"
pydantic = "^2.12.5"
pillow = "^12.1.0"
scapy = "^2.6.1"
netron = "^8.8.1"
absl-py = "^2.3.1"

torch = { version = "^2.9.1", optional = true }
torcheval = { version = "^0.0.7", optional = true }
# View model summaries in PyTorch!
torchinfo = { version = "^1.8.0", optional = true }
torchvision = { version = "^0.25.0", optional = true }
tensorrt = { version = "^10.12.0", optional = true }
onnx = { version = "^1.20.0", optional = true }
onnx-graphsurgeon = { version = "^0.5.8", optional = true }
onnxruntime-tools = { version = "^1.7.0", optional = true }
onnxruntime = { version = "^1.23.2", optional = true }
# `pip install --extra-index-url https://pypi.nvidia.com/ tensorrt-cu13-libs`
tensorrt-cu13-libs = { version = "^10.14.1", source = "nvidia", optional = true }
nvidia-cusolver-cu12 = { version = "^11.7.3.90", source = "nvidia", optional = true }
nvidia-cudnn-cu12 = { version = "^9.10.2.21", source = "nvidia", optional = true }

# `poetry install --extras gpu`
[tool.poetry.extras]
gpu = [
    "torch",
    "torcheval",
    "torchinfo",
    "torchvision",
    "tensorrt",
    "onnx",
    "onnx-graphsurgeon",
    "onnxconverter-common",
    "onnxruntime-tools",
    "onnxruntime",
]

# `poetry install --with llm`
[tool.poetry.group.llm.dependencies]
safetensors = "^0.7.0"
transformers = "^4.57.3"


[tool.poetry.group.dev.dependencies]
setuptools = "80.0.0" # `Tensorboard requires this version or below`
wheel = "^0.46.3"
cryptography = "^46.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
