[tool.poetry]
name = "dta-rust"
version = "1.0.0"
description = "A lightweight method for detecting extremely low-proportion dt in backbone networks."
authors = ["alpinebuster <imzqqq@hotmail.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Communications :: Tor",
]
package-mode = false  # Disable packaging mode, only for dependency management
# packages = [
#     { include = "src" },
# ]
# include = [
#     { path = "docs", format = "sdist" },
#     { path = "tests", format = "sdist" },
#     { path = "Cargo.toml", format = "sdist" },
#     { path = "Cargo.lock", format = "sdist" },
#     { path = "rust/Cargo.toml", format = "sdist" },
#     { path = "rust/build.rs", format = "sdist" },
#     { path = "rust/src/**", format = "sdist" },
# ]
# exclude = [
#     "src/*.so",
# ]

[[tool.poetry.source]]
name = "tsinghua"
# url = "https://pypi.doubanio.com/simple/"
# url = "https://mirrors.163.com/pypi/simple/"
# url = "https://mirrors.aliyun.com/pypi/simple/"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"
[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = "supplemental"
[[tool.poetry.source]]
name = "nvidia"
url = "https://pypi.nvidia.com"
priority = "explicit"

[tool.maturin]
manifest-path = "rust/Cargo.toml"
module-name = "src.src_rust"
features = ["pyo3/extension-module"]

[tool.poetry.build]
script = "pre_build.py"
generate-setup-file = true

[tool.poetry.dependencies]
python = ">=3.11,<=3.13"
# This is for building the rust components during "poetry install", which
# currently ignores the `build-system.requires` directive (c.f.
# https://github.com/python-poetry/poetry/issues/6154). Both `pip install` and
# `poetry build` do the right thing without this explicit dependency.
#
# This isn't really a dev-dependency, as `poetry install --no-dev` will fail,
# but the alternative is to add it to the main list of deps where it isn't
# needed.
setuptools_rust = ">=1.12.0"
attrs = "^24.2.0"
fastai = "^2.7.14"
scipy = "^1.12.0"
pandas = "^2.2.1"
ipywidgets = "^8.1.2"
seaborn = "^0.13.2"
scikit-learn = "^1.4.1.post1"
imbalanced-learn = "^0.12.0"
scapy = "^2.6.1"
keras = "^3.3.3"
requests = "^2.31.0"
matplotlib = "^3.8.4"
tqdm = "^4.66.4"
opencv-python = "^4.10.0.84"
pyyaml = "^6.0.1"
tensorboard = "^2.18.0"
torch-tb-profiler = "^0.4.3"
pydantic = "^2.7.4"
pillow = "^12.0.0"
huggingface-hub = "^0.26.5"
scikit-image = "^0.25.0"
xgboost = "^2.1.1"
tables = "^3.10.1"
thop = "^0.1.1.post2209072238"
pympler = "^1.1"
memory-profiler = "^0.61.0"
hyperopt = "^0.2.7"
dpkt = "^1.9.8"
statsmodels = "^0.14.4"
netron = "^8.0.4"
polygraphy-trtexec = "^0.0.9"
colored = "^2.2.4"
plotly = "^5.24.1"
numpy = "^2.3.4"
pytest = "^8.4.2"

pycuda = { version = "^2025.1.2", optional = true }
torch = { version = "^2.9.0", optional = true }
torcheval = { version = "^0.0.7", optional = true }
# View model summaries in PyTorch!
torchinfo = { version = "^1.8.0", optional = true }
torchvision = { version = "^0.24.0", optional = true }
onnx = { version = "^1.16.1", optional = true }
onnx-graphsurgeon = { version = "^0.5.2", optional = true }
onnxconverter-common = { version = "^1.14.0", optional = true }
onnxruntime-tools = { version = "^1.7.0", optional = true }
onnxruntime = { version = "^1.18.0", optional = true }

[tool.poetry.extras]
# `poetry install --extras gpu --extras local`
gpu = [
    # "pycuda",
    "torch",
    "torcheval",
    "torchinfo",
    "torchvision",
    "onnx",
    "onnx-graphsurgeon",
    "onnxconverter-common",
    "onnxruntime-tools",
    "onnxruntime",
]
local = []

[tool.poetry.group.dev.dependencies]
ipykernel = "^7.1.0"

[build-system]
# The upper bounds here are defensive, intended to prevent
# runtime errors caused by build system changes.
# We are happy to raise these upper bounds upon request,
# provided we check that it's safe to do so (i.e. that CI passes).
requires = [
    "poetry-core>=2.2.1",
    "setuptools>=80.9.0",
    "wheel>=0.45.1",
    "setuptools_rust>=1.12.0",
]
build-backend = "poetry.core.masonry.api"

[tool.cibuildwheel]
# Skip unsupported platforms (by us or by Rust).
# See https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip for the list of build targets.
# We skip:
#  - CPython 3.6 and 3.7: EOLed
#  - PyPy 3.7: we only support Python 3.8+
#  - musllinux i686: excluded to reduce number of wheels we build.
#  - PyPy on Aarch64 and musllinux on aarch64: too slow to build.
skip = "cp36* cp37* pp37* *-musllinux_i686 pp*aarch64 *-musllinux_aarch64"

# We need a rust compiler
before-all =  "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y --profile minimal"
environment= { PATH = "$PATH:$HOME/.cargo/bin" }

# For some reason if we don't manually clean the build directory we
# can end up polluting the next build with a .so that is for the wrong
# Python version.
before-build = "rm -rf {project}/build"
build-frontend = "build"
test-command = "python -c 'from src.src_rust import sum_as_string; print(sum_as_string(1, 2))'"
