name: Build Docker image

on:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:

env:
  DOCKER_IMAGE: imzqqq/arkime
  DOCKER_IMAGE_GHCR: ghcr.io/alpinebuster/arkime
  DOCKER_UBUNTU_VERSION: "24.04"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=latest,branches=main
            type=ref,event=tag
            type=sha
      - name: Docker meta for GHCR
        id: meta_ghcr
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_GHCR }}
          tags: |
            type=raw,value=latest,branches=main
            type=ref,event=tag
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GHCR
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/dev6.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            DOCKER_UBUNTU_VERSION=${{ env.DOCKER_UBUNTU_VERSION }}
          platforms: linux/amd64
      - name: Build and push GHCR image
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/dev6.Dockerfile
          push: true
          tags: ${{ steps.meta_ghcr.outputs.tags }}
          build-args: |
            DOCKER_UBUNTU_VERSION=${{ env.DOCKER_UBUNTU_VERSION }}
          platforms: linux/amd64
